### ISSUE TITLE
[GWONZI TT] CMS Open Think Tank

### ISSUE THREAD

**Issue by gwonzi** [gwonzi/gwonzi.github.io#12]
This is more of an open forum for the short term and long term for Gwonzi TT (Table Top)

***Logo***
So for an easy starter, I like it being called Gwonzi TT. Primarily because I foresee it being much easier to create a logo for it adding in just the letters "TT" (like how Gwonzi EDH just had "EDH" added in to the Gwonzi logo with different font) instead of having to spell out "Table Top" or "Board Games" completely. 
I think of it more as a branding approach, and think TT is fine. But is this something you specifically hate? 

***Short Term***
My vision of Gwonzi TT is to be a lot like Gwonzi EDH. The video model of what we are doing with Gwonzi EDH is very simplistic, YET STILL CREATES A HUGE LIST OF SHIT FOR ME TO DO FOR PRODUCTION. Like, its a lot. All of your work on narration and the website I appreciate so much, but the production side is the suck man. So, that being said, I would love to keep the same model for Gwonzi TT since it is a production/ editing flow I'm used to. Additionally, I think we fall into a niche/ style that doesn't exist directly for the TT community, so in my mind it doubles down its benefit. 

That all being said: following that model,  I feel like we really invite only certain types of games for now. The games I see that fit this bill very easily are basically any actual "board" game, where minimal social/ vocal interaction is necessary. Games that are almost like a magic flow, where players have turns, actions and influence on a central area where all can see. The games I see that work in this model are:
- Lords of Waterdeep
- Concordia
- Castles of Burgandy
- Lords of Vegas (or whatever its called)
- Settlers of Catan
- Ticket to Ride
- Carcasonne

There are probably more, but you see the consistent type of game style these games present. Games that I think do not fit this production model are:
- The Resistance
- Concept
- Sheriff of Nottingham
- Betrayal of House on the Hill
- Spyfall

***Long Term***
Now. I know I sound a little lazy and selfish regarding the editing work flow, but the consistency against the model we have in Gwonzi EDH is not the only reason why I laid things out as I did in the Short Term section. Another reason is our production equipment assets. 
I think the future of Gwonzi TT could be a lot more, and be very different than Gwonzi EDH. But I think that just requires a lot more of a production approach than we can really take on financially or bandwidth wise just yet. For the list of games above that I say do not fit the current model, I think they would benefit from multiple camera angles, a constructed approach on live audio capture, and both of those GREATLY INCREASES MY ALREADY AWFUL PRODUCTION/ EDITING TIME.
Let me be clear, no where, in here, am I bitching about my work load. 
What I'm being mindful of is:
a) How much does what we want to do cost? Do we already have it? Do we need more?
b) How long will it honestly take me to output it?
I want to pump content in the early going and one Gwonzi EDH video, with the model we have, took, A LOT of time. I basically worked from home two days and literally did just that. That is not sustainable if considering we add more lololololol. 
Therefore. The long term of what this could be, adding these sorts of games, and new productions approaches, I think is dependent on the Gwonzi business' success and what happens with it. 

However, for the here and now, I feel like sticking to the existing EDH model is a way to create content a little more quickly and it be good content. That way we pile up our resume, and can expand from there.

**Comment by chrhyman** [comment]
After our first recording session didn't go so ideally for TT, and after the discussions we had with Shelby, I'm just gonna close this issue. I think we've addressed pretty much all of the things that came up in this discussion.

Resolutions:

- Static top-down is nearly impossible for TT
- More camera angels and audio work > Footage ++ > Storage required ++ > Editing time ++
- BUT it also increases the video dynamicity and personality
- It also broadens the types of games we can cover (such as social games)
